# Generated by Django 4.2.13 on 2024-06-15 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
