# Generated by Django 5.0.6 on 2024-05-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
