# Generated by Django 4.2.13 on 2024-06-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='previous_closed',
            new_name='previous_close',
        ),
    ]
