# Generated by Django 5.0.6 on 2024-05-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_to',
            new_name='updated_at',
        ),
    ]
