# Generated by Django 5.0.6 on 2024-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_rename_upload_to_upload_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
